FROM node:latest
CMD mkdir /usr/local/socketio
ADD . /usr/local/socketio/
WORKDIR /usr/local/socketio
RUN npm install

ENV NOTIFICATION_SECRET NOTIFICATION_SECRET
ENV NOTIFICATION_KEY NOTIFICATION_KEY
ENV PRODUCTION true

#VOLUME [ "/usr/local/socketio" ]
EXPOSE 5015
EXPOSE 3000

ENTRYPOINT [ "node" ]
CMD ["index.js"]
